apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cilium-portmap
  namespace: kube-system
  labels:
    app: cilium-portmap
spec:
  selector:
    matchLabels:
      name: cilium-portmap
  template:
    metadata:
      labels:
        name: cilium-portmap
    spec:
      containers:
      - name: cilium-portmap
        image: snormore/cilium-portmap:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: etc-cni-netd
            mountPath: /host/etc/cni/net.d
      volumes:
        - name: etc-cni-netd
          hostPath:
            path: /host/etc/cni/net.d
      priorityClassName: system-node-critical
      tolerations:
      - operator: "Exists"